services:
  redis:
    container_name: redis
    image: redis/redis-stack-server:7.2.0-v18
    environment:
      TZ: 'America/Vancouver'
      #REDIS_ARGS: --appendonly yes --requirepass admin
      #REDIS_ARGS: --appendonly yes
    ports:
      - 16379:6379
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

